# Generated by Django 5.0.6 on 2025-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='liveranking',
            name='unique_ranking_per_competition_category_type_round',
        ),
        migrations.RemoveConstraint(
            model_name='liverankingentry',
            name='unique_participant_per_ranking',
        ),
        migrations.RemoveConstraint(
            model_name='teamranking',
            name='unique_team_per_competition',
        ),
        migrations.AlterUniqueTogether(
            name='liveranking',
            unique_together={('competition', 'category', 'ranking_type', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='liverankingentry',
            unique_together={('ranking', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='teamranking',
            unique_together={('competition', 'team_name')},
        ),
    ]
