# Generated by Django 5.0.7 on 2025-07-03 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_participants", models.IntegerField()),
                ("completed_evaluations", models.IntegerField()),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "db_table": "ranking_snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RankingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField()),
                ("previous_position", models.IntegerField(blank=True, null=True)),
                ("position_change", models.IntegerField(default=0)),
                ("total_score", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "percentage_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("judge_scores", models.JSONField(default=dict)),
                ("evaluations_completed", models.IntegerField(default=0)),
                ("evaluations_total", models.IntegerField(default=0)),
                ("is_tied", models.BooleanField(default=False)),
                ("tied_with", models.JSONField(default=list)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.registration",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="rankings.rankingsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "ranking_entries",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LiveRankingUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("POSITION_CHANGE", "Cambio de posición"),
                            ("SCORE_UPDATE", "Actualización de puntuación"),
                            ("NEW_PARTICIPANT", "Nuevo participante"),
                            ("EVALUATION_COMPLETE", "Evaluación completada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("affected_participants", models.JSONField(default=list)),
                ("change_data", models.JSONField(default=dict)),
                ("broadcasted", models.BooleanField(default=False)),
                ("broadcast_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "db_table": "live_ranking_updates",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["competition", "category", "timestamp"],
                        name="live_rankin_competi_28b18d_idx",
                    ),
                    models.Index(
                        fields=["broadcasted"], name="live_rankin_broadca_8e6987_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calculation_start", models.DateTimeField(auto_now_add=True)),
                ("calculation_end", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("participants_processed", models.IntegerField(default=0)),
                ("evaluations_processed", models.IntegerField(default=0)),
                ("position_changes", models.JSONField(default=list)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ranking_calculations",
                "ordering": ["-calculation_start"],
                "indexes": [
                    models.Index(
                        fields=["competition", "category"],
                        name="ranking_cal_competi_b0ba7b_idx",
                    ),
                    models.Index(
                        fields=["calculation_start"],
                        name="ranking_cal_calcula_0f3c7d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_calculate", models.BooleanField(default=True)),
                ("calculation_interval", models.IntegerField(default=30)),
                (
                    "tie_break_method",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Mayor porcentaje"),
                            ("COLLECTIVE_MARKS", "Notas colectivas"),
                            ("TECHNICAL_SCORE", "Puntuación técnica"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                ("broadcast_enabled", models.BooleanField(default=True)),
                ("broadcast_interval", models.IntegerField(default=5)),
                ("show_percentages", models.BooleanField(default=True)),
                ("show_judge_breakdown", models.BooleanField(default=True)),
                ("show_position_changes", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "db_table": "ranking_configurations",
                "indexes": [
                    models.Index(
                        fields=["competition", "category"],
                        name="ranking_con_competi_246c68_idx",
                    )
                ],
                "unique_together": {("competition", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="rankingsnapshot",
            index=models.Index(
                fields=["competition", "category", "is_current"],
                name="ranking_sna_competi_04fc28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshot",
            index=models.Index(
                fields=["timestamp"], name="ranking_sna_timesta_6f265c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rankingentry",
            index=models.Index(
                fields=["snapshot", "position"], name="ranking_ent_snapsho_904630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rankingentry",
            index=models.Index(
                fields=["participant"], name="ranking_ent_partici_305d97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rankingentry",
            unique_together={("snapshot", "participant")},
        ),
    ]
