# Generated by Django 5.0.7 on 2025-06-28 21:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("organizer", "Organizador"),
                            ("judge", "Juez"),
                            ("spectator", "Espectador"),
                        ],
                        default="spectator",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="País"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("login", "Iniciar Sesión"),
                            ("logout", "Cerrar Sesión"),
                            ("permission_grant", "Otorgar Permiso"),
                            ("permission_revoke", "Revocar Permiso"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Recurso"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID del Recurso"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JudgeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fei_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ID FEI",
                    ),
                ),
                (
                    "certification_level",
                    models.CharField(
                        choices=[
                            ("level1", "Nivel 1"),
                            ("level2", "Nivel 2"),
                            ("level3", "Nivel 3"),
                            ("level4", "Nivel 4"),
                            ("level5", "Nivel 5"),
                            ("international", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Certificación",
                    ),
                ),
                (
                    "disciplines",
                    models.JSONField(
                        default=list,
                        help_text="Lista de disciplinas en las que está certificado",
                        verbose_name="Disciplinas",
                    ),
                ),
                (
                    "certification_date",
                    models.DateField(verbose_name="Fecha de Certificación"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Expiración"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Licencia"
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Biografía"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Años de Experiencia"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text="Idiomas que habla",
                        verbose_name="Idiomas",
                    ),
                ),
                (
                    "is_active_judge",
                    models.BooleanField(default=True, verbose_name="Juez Activo"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Juez",
                "verbose_name_plural": "Perfiles de Jueces",
            },
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Organización"
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("federation", "Federación"),
                            ("club", "Club"),
                            ("private", "Organizador Privado"),
                            ("educational", "Institución Educativa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Organización",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Licencia"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Sitio Web")),
                ("address", models.TextField(max_length=500, verbose_name="Dirección")),
                (
                    "contact_person",
                    models.CharField(
                        max_length=100, verbose_name="Persona de Contacto"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de Contacto"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                        verbose_name="Teléfono de Contacto",
                    ),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Establecimiento"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_verified_organizer",
                    models.BooleanField(
                        default=False, verbose_name="Organizador Verificado"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Organizador",
                "verbose_name_plural": "Perfiles de Organizadores",
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("competitions", "Competencias"),
                            ("scoring", "Puntuación"),
                            ("rankings", "Rankings"),
                            ("users", "Usuarios"),
                            ("reports", "Reportes"),
                            ("audit", "Auditoría"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "Ver"),
                            ("create", "Crear"),
                            ("edit", "Editar"),
                            ("delete", "Eliminar"),
                            ("manage", "Administrar"),
                        ],
                        max_length=10,
                        verbose_name="Permiso",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Otorgado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Usuario",
                "verbose_name_plural": "Permisos de Usuarios",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified"], name="users_user_is_veri_9ce429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="users_audit_user_id_4b4ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="users_audit_action_962101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "timestamp"],
                name="users_audit_resourc_865474_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="judgeprofile",
            index=models.Index(fields=["fei_id"], name="users_judge_fei_id_b74ac4_idx"),
        ),
        migrations.AddIndex(
            model_name="judgeprofile",
            index=models.Index(
                fields=["certification_level"], name="users_judge_certifi_fbb380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgeprofile",
            index=models.Index(
                fields=["is_active_judge"], name="users_judge_is_acti_3b2896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizerprofile",
            index=models.Index(
                fields=["organization_type"], name="users_organ_organiz_d4093c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizerprofile",
            index=models.Index(
                fields=["is_verified_organizer"], name="users_organ_is_veri_2735e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpermission",
            index=models.Index(
                fields=["user", "module"], name="users_userp_user_id_22c175_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("user", "module", "permission")},
        ),
    ]
