# Generated by Django 5.0.7 on 2025-06-30 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerprofile",
            name="contact_phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[\\d\\s\\-\\(\\)]{7,20}$"
                    )
                ],
                verbose_name="Teléfono de Contacto",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[\\d\\s\\-\\(\\)]{7,20}$"
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
    ]
