# Generated by Django 5.0.7 on 2025-07-01 20:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("users", "0002_alter_organizerprofile_contact_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_number",
                    models.PositiveIntegerField(
                        help_text="Número del ejercicio (1-25 según hojas Excel)"
                    ),
                ),
                (
                    "exercise_name",
                    models.CharField(
                        help_text="Nombre descriptivo del ejercicio", max_length=200
                    ),
                ),
                (
                    "coefficient",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                        help_text="Coeficiente multiplicador FEI (1, 2, 3, 4, 5)",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("10.0"),
                        help_text="Puntuación máxima para este ejercicio (normalmente 10.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("10.0")),
                        ],
                    ),
                ),
                (
                    "is_collective_mark",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es una nota de conjunto (aparece al final de las hojas Excel)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de presentación en la interfaz"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción detallada del ejercicio"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_parameters",
                        to="competitions.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro de Evaluación",
                "verbose_name_plural": "Parámetros de Evaluación",
                "db_table": "scoring_evaluation_parameters",
                "ordering": ["category", "order", "exercise_number"],
                "unique_together": {("category", "exercise_number")},
            },
        ),
        migrations.CreateModel(
            name="JudgePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("C", "Posición C"),
                            ("B", "Posición B"),
                            ("H", "Posición H"),
                            ("M", "Posición M"),
                            ("E", "Posición E"),
                            ("K", "Posición K"),
                            ("F", "Posición F"),
                            ("S", "Posición S"),
                        ],
                        help_text="Posición del juez en la pista",
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_positions",
                        to="competitions.competition",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.judgeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posición de Juez",
                "verbose_name_plural": "Posiciones de Jueces",
                "db_table": "scoring_judge_positions",
                "unique_together": {("competition", "judge", "position")},
            },
        ),
        migrations.CreateModel(
            name="ScoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Puntuación otorgada (0.0 - 10.0 en incrementos de 0.5)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("10.0")),
                        ],
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Justificación obligatoria para puntuaciones ≤3.0 o ≥8.5",
                    ),
                ),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evaluation_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scoring.evaluationparameter",
                    ),
                ),
                (
                    "judge_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scoring.judgeposition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="competitions.registration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scores_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
                "db_table": "scoring_score_entries",
                "ordering": [
                    "participant",
                    "evaluation_parameter__order",
                    "evaluation_parameter__exercise_number",
                ],
                "unique_together": {
                    ("participant", "judge_position", "evaluation_parameter")
                },
            },
        ),
        migrations.CreateModel(
            name="ScoreAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Creación"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("review", "Revisión"),
                            ("finalize", "Finalización"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "old_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "new_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("old_justification", models.TextField(blank=True)),
                ("new_justification", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(help_text="Razón del cambio")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "score_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="scoring.scoreentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "scoring_audit_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="JudgeEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma total de puntuaciones ponderadas",
                        max_digits=6,
                    ),
                ),
                (
                    "total_possible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación máxima posible",
                        max_digits=6,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje FEI calculado",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("reviewed", "Revisada"),
                            ("finalized", "Finalizada"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "general_comments",
                    models.TextField(
                        blank=True, help_text="Comentarios generales sobre la actuación"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="competitions.registration",
                    ),
                ),
                (
                    "judge_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="scoring.judgeposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Juez",
                "verbose_name_plural": "Evaluaciones de Jueces",
                "db_table": "scoring_judge_evaluations",
                "ordering": ["-completed_at", "-updated_at"],
                "unique_together": {("participant", "judge_position")},
            },
        ),
    ]
