# Generated by Django 5.0.6 on 2025-09-26 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_offline_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offlinestorage',
            name='unique_user_device_storage_key',
        ),
        migrations.RenameIndex(
            model_name='offlinestorage',
            new_name='sync_offlin_user_id_c522e3_idx',
            old_name='sync_offlinestorage_user_device_idx',
        ),
        migrations.RenameIndex(
            model_name='offlinestorage',
            new_name='sync_offlin_storage_df21ba_idx',
            old_name='sync_offlinestorage_storage_type_idx',
        ),
        migrations.RenameIndex(
            model_name='offlinestorage',
            new_name='sync_offlin_is_sync_0269f4_idx',
            old_name='sync_offlinestorage_is_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='offlinestorage',
            new_name='sync_offlin_sync_pr_aa76a8_idx',
            old_name='sync_offlinestorage_sync_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='sync_syncac_sync_se_1aaaab_idx',
            old_name='sync_syncaction_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='sync_syncac_action__dcabf1_idx',
            old_name='sync_syncaction_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='sync_syncac_priorit_3085f2_idx',
            old_name='sync_syncaction_priority_status_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='sync_syncac_content_b5833b_idx',
            old_name='sync_syncaction_content_object_idx',
        ),
        migrations.RenameIndex(
            model_name='syncsession',
            new_name='sync_syncse_user_id_4a3c95_idx',
            old_name='sync_syncsession_user_device_idx',
        ),
        migrations.RenameIndex(
            model_name='syncsession',
            new_name='sync_syncse_status_25e40e_idx',
            old_name='sync_syncsession_status_idx',
        ),
        migrations.RenameIndex(
            model_name='syncsession',
            new_name='sync_syncse_start_t_f96e76_idx',
            old_name='sync_syncsession_start_time_idx',
        ),
        migrations.AlterUniqueTogether(
            name='offlinestorage',
            unique_together={('user', 'device_id', 'storage_key')},
        ),
    ]
