# Generated by Django 5.0.7 on 2025-06-30 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INTRO", "Introductorio"),
                            ("PRELIMINARY", "Preliminar"),
                            ("NOVICE", "Novato"),
                            ("TRAINING", "Entrenamiento"),
                            ("MODIFIED", "Modificado"),
                            ("INTERMEDIATE", "Intermedio"),
                            ("ADVANCED", "Avanzado"),
                            ("CCI1", "CCI1*"),
                            ("CCI2", "CCI2*"),
                            ("CCI3", "CCI3*"),
                            ("CCI4", "CCI4*"),
                            ("CCI5", "CCI5*"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_age_rider",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(80),
                        ]
                    ),
                ),
                (
                    "max_age_rider",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(80),
                        ],
                    ),
                ),
                (
                    "min_age_horse",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "fei_parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parámetros específicos FEI para esta categoría",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["discipline", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                ("fei_code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("breed", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MARE", "Yegua"),
                            ("STALLION", "Semental"),
                            ("GELDING", "Castrado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("owner", models.CharField(max_length=200)),
                ("country_of_birth", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=50, unique=True)),
                ("vaccination_current", models.BooleanField(default=False)),
                ("health_certificate_valid", models.BooleanField(default=False)),
                ("insurance_valid", models.BooleanField(default=False)),
                (
                    "fei_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("national_registration", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caballo",
                "verbose_name_plural": "Caballos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "venue",
                    models.CharField(
                        help_text="Lugar de la competencia", max_length=200
                    ),
                ),
                ("address", models.TextField(help_text="Dirección completa del venue")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("OPEN", "Abierta para inscripciones"),
                            ("REGISTRATION_CLOSED", "Inscripciones cerradas"),
                            ("IN_PROGRESS", "En progreso"),
                            ("SCORING", "En calificación"),
                            ("COMPLETED", "Completada"),
                            ("CANCELLED", "Cancelada"),
                            ("SUSPENDED", "Suspendida"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "max_total_participants",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                ("allow_late_registration", models.BooleanField(default=False)),
                (
                    "late_registration_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "weather_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "Soleado"),
                            ("CLOUDY", "Nublado"),
                            ("RAINY", "Lluvioso"),
                            ("WINDY", "Ventoso"),
                            ("MIXED", "Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ground_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIRM", "Firme"),
                            ("GOOD", "Bueno"),
                            ("SOFT", "Blando"),
                            ("HEAVY", "Pesado"),
                            ("FROZEN", "Congelado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperatura en Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fei_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("is_fei_sanctioned", models.BooleanField(default=False)),
                (
                    "regulations",
                    models.TextField(
                        blank=True,
                        help_text="Regulaciones específicas de la competencia",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competencia",
                "verbose_name_plural": "Competencias",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "entry_fee_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("special_requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Competencia",
                "verbose_name_plural": "Categorías de Competencia",
                "ordering": ["order", "category__name"],
                "unique_together": {("competition", "category")},
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="categories",
            field=models.ManyToManyField(
                through="competitions.CompetitionCategory", to="competitions.category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="competitions.discipline",
            ),
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("nationality", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                (
                    "fei_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("license_type", models.CharField(max_length=50)),
                ("license_valid_until", models.DateField()),
                ("insurance_valid", models.BooleanField(default=False)),
                ("medical_certificate_valid", models.BooleanField(default=False)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categorías en las que puede competir",
                        to="competitions.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jinete",
                "verbose_name_plural": "Jinetes",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("discipline", "code")},
        ),
        migrations.CreateModel(
            name="JudgeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRESIDENT", "Presidente del Jurado"),
                            ("MEMBER", "Miembro del Jurado"),
                            ("GROUND_JURY", "Jurado de Tierra"),
                            ("TECHNICAL_DELEGATE", "Delegado Técnico"),
                            ("COURSE_DESIGNER", "Diseñador de Pista"),
                            ("VETERINARIAN", "Veterinario"),
                            ("STEWARD", "Comisario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Orden en el panel de jueces"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "travel_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("accommodation_provided", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_assignments",
                        to="competitions.competitioncategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_judge_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Juez",
                "verbose_name_plural": "Asignaciones de Jueces",
                "ordering": ["order", "role"],
                "unique_together": {("competition_category", "judge", "role")},
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CONFIRMED", "Confirmada"),
                            ("PAID", "Pagada"),
                            ("CANCELLED", "Cancelada"),
                            ("WAITLIST", "Lista de espera"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "start_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Número de dorsal", null=True
                    ),
                ),
                (
                    "entry_fee_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("special_requirements", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.competitioncategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.horse",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.rider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "ordering": ["registered_at"],
                "unique_together": {
                    ("competition_category", "rider", "horse"),
                    ("competition_category", "start_number"),
                },
            },
        ),
    ]
